Estimate/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Estimate.Models;
using System.Configuration;

namespace Estimate.Controllers
{
    public class ProductController : Controller
    {
        // GET: Product
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Search(FormCollection _FormCollction)
        {
            string ConnectString = ConfigurationManager.ConnectionStrings["EstimateConnectionString"].ConnectionString;
            using (var db = new DataClasses1DataContext(ConnectString))
            {
                ProductResult _ = new ProductResult();
                try
                {
                    var _result = db.M商品.First(x => x.JANCD == _FormCollction["Code"]);

                    _ = new ProductResult()
                    {
                        JANCD = _result.JANCD,
                        Product_Name = _result.商品名,
                        Kana = _result.カタカナ名,
                        Maker_CD = _result.メーカーCD,
                        Supplier_CD = _result.仕入先CD,
                        Order_CD = _result.発注先CD,
                        RegistDay = _result.登録日時,
                        MAX_Kubun = (int)_result.最大区分,
                        MAX_Kikaku = _result.最大規格,
                        MAX_Tanni = _result.最大単位,
                        MAX_Keisu = (decimal)_result.最大係数,
                        MAX_Nyusu = (decimal)_result.最大入数,
                        MID_Kubun = (int)_result.中間区分, 
                        MID_Kikaku = _result.中間規格,
                        MID_Tanni =  _result.中間単位,
                        MID_Keisu = (decimal) _result.中間係数,
                        MID_Nyusu = (decimal) _result.中間入数,
                        MIN_Kubun = (int) _result.最小区分,
                        MIN_Kikaku = _result.最小規格,
                        MIN_Tanni = _result.最小単位,
                        MIN_Keisu = (decimal) _result.最小係数,
                        MIN_Nyusu = (decimal) _result.最小入数,
                        ExpirationDay = (decimal) _result.賞味期間,
                        Purchase_Tanka = (decimal) _result.仕入単価,
                        Change_Tanka = (decimal) _result.変更前単価,
                        SellDay = _result.販売期限日付,
                        ChangeDay = _result.単価変更日付,
                        Notes = _result.備考
                    };
                }
                catch { }
                return PartialView("Detail", _);
            }
        }
    }
}

Estimate/Controllers/TopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Estimate.Controllers
{
    public class TopController : Controller
    {
        // GET: Top
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult User(FormCollection _FormCollection)
        {
            return RedirectToAction("Index", "User");
        }

        public ActionResult Estimate(FormCollection _FormCollection)
        {
            return RedirectToAction("Index", "Estimate");
        }

        public ActionResult Supplier(FormCollection _FormCollection)
        {
            return RedirectToAction("Index", "Supplier");
        }

        public ActionResult Order(FormCollection _FormCollection)
        {
            return RedirectToAction("Index", "Order");
        }

        public ActionResult Product(FormCollection _FormCollection)
        {
            return RedirectToAction("Index", "Product");   
        }

        public ActionResult Customer(FormCollection _FormCollection)
        {
            return RedirectToAction("Index", "Customer");
        }
    }
}

Estimate/Views/Product/Detail.cshtml
@model Estimate.Models.ProductResult

<div class="">
    <div class="text">
        @*JANCD*@
        <div class="">
            <div class="text">JANCD</div>
            <div class="text"><input type="text" id="" name="" value="@Model.JANCD" readonly="" /></div>
            <div class="cls"></div>
        </div>

        @*商品名*@
        <div class="">
            <div class="text">商品名</div>
            <div class=""><input type="text" id="Product_Name" name="" value="@Model.Product_Name" readonly="" /></div>
            <div class="cls"></div>
        </div>

        @*カタカナ名*@
        <div class="">
            <div class="text">カタカナ名</div>
            <div class=""><input type="text" id="" name="" value="@Model.Kana" readonly="" /></div>
            <div class="cls"></div>
        </div>

        @*メーカーCD*@
        <div class="">
            <div class="text">メーカーCD</div>
            <div class="text"><input type="text" id="" name="" value="@Model.Maker_CD" readonly="" /></div>
            <div class=""><input type="text" id="" name="" /></div>
            <div class="cls"></div>
        </div>

        @*仕入先CD*@
        <div class="">
            <div class="text">仕入先CD</div>
            <div class="text"><input type="text" id="" name="" value="@Model.Supplier_CD" readonly="" /></div>
            <div class=""><input type="text" id="" name="" /></div>
            <div class="cls"></div>
        </div>

        @*発注先CD*@
        <div class="">
            <div class="text">発注先CD</div>
            <div class="text"><input type="text" id="" name="" value="@Model.Order_CD" readonly="" /></div>
            <div class=""><input type="text" id="" name="" /></div>
            <div class="cls"></div>
        </div>
    </div>

    <div class="" align="right">
        <div class="text">登録日</div>
        <div class=""><input type="text" id="" name="" value="@Model.RegistDay" readonly="" /></div>
        @*<div class=""><textarea name="" cols="30" rows="5" readonly="" ></textarea></div>*@
    </div>
</div>
<div class="cls"></div>

<div class="">
    @*最大区分*@
    <div class="text" style="padding: 10px; margin-bottom: 10px; border: 1px solid #333333;">
        <div class="">最大</div>
        <div class="">
            <div class="text">区分</div>
            <div class="text"><input type="text" id="" name="" value="@Model.MAX_Kubun" readonly="" /></div>
            <div class=""><input type="text" id="" name="" /></div>

            <div class="text">規格</div>
            <div class=""><input type="text" id="" name="" value="@Model.MAX_Kikaku" readonly="" /></div>

            <div class="text">単位</div>
            <div class=""><input type="text" id="" name="" value="@Model.MAX_Tanni" readonly="" /></div>

            <div class="text">係数</div>
            <div class=""><input type="text" id="" name="" value="@Model.MAX_Keisu" readonly="" /></div>

            <div class="text">入数</div>
            <div class=""><input type="text" id="" name="" @Model.MAX_Nyusu readonly="" /></div>
        </div>
    </div>

    @*中間区分*@
    <div class="text" style="padding: 10px; margin-bottom: 10px; border: 1px solid #333333;">
        <div class="">中間</div>
        <div class="">
            <div class="text">区分</div>
            <div class="text"><input type="text" id="" name="" value="@Model.MID_Kubun" readonly="" /></div>
            <div class=""><input type="text" id="" name="" /></div>

            <div class="text">規格</div>
            <div class=""><input type="text" id="" name="" value="@Model.MID_Kikaku" readonly="" /></div>

            <div class="text">単位</div>
            <div class=""><input type="text" id="" name="" value="@Model.MID_Tanni" readonly="" /></div>

            <div class="text">係数</div>
            <div class=""><input type="text" id="" name="" value="@Model.MID_Keisu" readonly="" /></div>

            <div class="text">入数</div>
            <div class=""><input type="text" id="" name="" value="@Model.MID_Nyusu" readonly="" /></div>
        </div>
    </div>

    @*最小区分*@
    <div class="text" style="padding: 10px; margin-bottom: 10px; border: 1px solid #333333;">
        <div class="">最小</div>
        <div class="">
            <div class="text">区分</div>
            <div class="text"><input type="text" id="" name="" value="@Model.MIN_Kubun" readonly="" /></div>
            <div class=""><input type="text" id="" name="" /></div>

            <div class="text">規格</div>
            <div class=""><input type="text" id="" name="" value="@Model.MIN_Kikaku" readonly="" /></div>

            <div class="text">単位</div>
            <div class=""><input type="text" id="" name="" value="@Model.MIN_Tanni" readonly="" /></div>

            <div class="text">係数</div>
            <div class=""><input type="text" id="" name="" value="@Model.MIN_Keisu" readonly="" /></div>

            <div class="text">入数</div>
            <div class=""><input type="text" id="" name="" value="@Model.MIN_Nyusu" readonly="" /></div>
        </div>

    </div>
    <div class="cls"></div>
</div>

@**@
<div class="">
    <div class="text">
        <div class="text">賞味期限</div>
        <div class=""><input type="text" id="" name="" size="5" value="@Model.ExpirationDay" readonly="" />日間</div>
    </div>

    <div class="">
        <div class="text">販売期限日</div>
        <div class=""><input type="text" id="" name="" value="@Model.SellDay" readonly="" /></div>
        <div class="cls"></div>
    </div>


    <div class="text">
        <div class="text">仕入単価</div>
        <div class=""><input type="text" id="Purchase_Tanka" name="" value="@Model.Purchase_Tanka" readonly="" /></div>
    </div>

    <div class="">
        <div class="text">単価変更日</div>
        <div class=""><input type="text" id="" name="" value="@Model.ChangeDay" readonly="" /></div>
        <div class="cls"></div>
    </div>

    <div class="">
        <div class="text">変更前単価(旧単価)</div>
        <div class=""><input type="text" id="" name="" value="@Model.Change_Tanka" readonly="" /></div>
    </div>

</div>

@*備考欄*@
<div class="">
    <div class="text">備考</div>
    <div class=""><textarea name="" cols="30" rows="5" value="@Model.Notes" readonly="" ></textarea></div>
    <div class="cls"></div>
</div>

Estimate/Views/Product/Index.cshtml
@{
    var _model = ViewBag.Details as Estimate.Models.ProductResult;
}

<link rel="stylesheet" href="~/Content/apl.css" type="text/css" />
<script src="~/Scripts/jquery-1.10.2.js"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>

@*戻るボタン*@
@using (Html.BeginForm("Index", "Top", FormMethod.Post))
{
    <div class="text">
        <div class=""><input type="submit" value="戻る" id="" name="" /></div>
        <div class="cls"></div>
    </div>
}

@*閉じるボタン*@
<div class="" >
    <div class=""><input type="button" value="閉じる" @*onClick="window.close()"*@ id="close" name="" /></div>
    <div class="cls"></div>
</div>

<div style="padding: 10px; margin-bottom: 10px; border: 1px solid #333333;">
    <h4 class="text">商品マスタ検索</h4>
    <div class="" align="right">
        <script language="JavaScript">
                myD       = new Date();

                myYear    = myD.getYear()
                myYear4   = (myYear < 2000) ? myYear+1900 : myYear;
                myMonth   = myD.getMonth() + 1;
                myDate    = myD.getDate();

                myMess1   = myYear4 + "年" + myMonth + "月" + myDate + "日";
                myMess    = myMess1 + " " ;
                document.write( myMess );

        </script>
    </div>

@using (Ajax.BeginForm("Search", "Product",
    new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "Result" }))
{
    <div class="" align="right">
        <input type="text" id="Code" name="Code" placeholder="商品コード・名前を入力" />
        <input type="submit" value="検索" id="" name="" />
    </div>
}
    
</div>

<div id="Result"></div>

<script src="http://code.jquery.com/jquery-1.12.4.js"></script>
<script language="javascript">
    $(function () {
        //検索結果を親ウィンドウに渡す
        $('#close').click(function () {
            
            var _Target = window.opener.document.getElementById("CallbackID").value;
            window.opener.document.getElementById(_Target).value = document.getElementById("Product_Name").value;

            var _TargetTanka = window.opener.document.getElementById("CallbackTanka").value;
            window.opener.document.getElementById(_TargetTanka).value = document.getElementById("Purchase_Tanka").value;

            window.close();
            //return false;
        })
    });

</script>